package com.example.android_nixie_v2

enum class BluetoothState {
    IDLE, WAIT_FOR_CONNECTION, CONNECTED, WAIT_FOR_MTU_CHANGE, WAIT_FOR_WIFI_READ, WAIT_FOR_OACP_DESC_WRITE, WAIT_FOR_OLCP_DESC_WRITE, WAIT_FOR_WIFI_DESC_WRITE, WAIT_FOR_FILTER_SET, WAIT_FOR_FIRST, WAIT_FOR_READ_ALARM, WAIT_FOR_READ_ID, WAIT_FOR_NEXT, ALL_SET
}